### ISSUE TITLE
Roadmap for V2 of the ML Model Extension

### ISSUE THREAD

**Issue by fmigneault** [crim-ca/mlm-extension#4]
## :rocket: Feature Request

*originally posted on https://github.com/crim-ca/dlm-extension/issues/7*

Below are acceptance criteria for #2 the new version of the ML Model Extension. After all these items are done I think #2 is ready to merge and we can publish a new version 2 release to https://github.com/stac-extensions/ml-model/issues . I'm working on most of these, let me know if you think other acceptance criteria should be included cc @fmigneault 

- [x] Incorporate feedback from @fmariv and others at @earthpulse 
    - I had a meeting with @fmariv, they're keen to review the extension, provide feedback and see if we can align it more with general ML use cases. They're working on supporting the STAC extension ecosystem for ML as a part of the [EOTDL](https://www.eotdl.com/) initiative
    - https://hackmd.io/DBRF1sQCS1WmSqygJNKQJQ?view
    - feel free to comment first and then submit a PR against https://github.com/rbavery/dlm-extension/tree/validate
- [x] address #5 
    - this will involve segregating flat fields from objects that are not meant to be searched on and are instead used for inference model loading, model input and output processing, and documenting in detail the accelerator and runtime details needed to run the model
- [x] ~~#4 by creating output objects for common detection tasks. At a minimum, start with single label classification, semantic segmentation, object detection. This will help resolve common ambiguities when interpreting model outputs, like the bbox coordinate ordering for object detection.~~ EDIT this can be left for after the v2 release
- [x] resolve #3, deciding how to refer to model extension metadata. within it's own STAC item/collection json or are these fields composed with common metadata in STAC json representing a spatiotemporal asset?
- [x] https://github.com/crim-ca/dlm-extension/pull/2#discussion_r1446651049 create an example and schema for the final spec
- [x] reorganize and update the stac_model extension validation and serialization package according to the final spec: https://github.com/crim-ca/dlm-extension/pull/2#issuecomment-1882002335
- [x] https://github.com/rbavery/dlm-extension/pull/2
- [x] consider inputs from user feedback (https://github.com/stac-extensions/ml-model/issues/13)
- [x] consider community examples applying DLM (https://github.com/sentinel-hub/stac-ml-example) 
- [x] #8 
- [x] #9 
- [x] #12
- [x] #13
- [x] integrate JSON schema representing new properties/fields (mix of https://github.com/crim-ca/dlm-extension/tree/main/json-schema and https://github.com/rbavery/dlm-extension/pull/1)
- [x] #14
- [x] https://github.com/stac-extensions/classification/issues/48
- [ ] https://github.com/stac-extensions/example-links/issues/4
- [ ] https://github.com/stac-extensions/processing/issues/31
- [ ] https://github.com/stac-extensions/processing/pull/33
- [ ] consideration of `end_datetime: null` not supported by STAC Core spec 
  (https://github.com/radiantearth/stac-spec/issues/1268)
  - [ ] new issue to track for the specific use case: https://github.com/radiantearth/stac-spec/issues/1161

**Comment by fmigneault** [comment]
Remaining issues moved to https://github.com/stac-extensions/mlm/issues/28 and https://github.com/stac-extensions/mlm/issues/29.
